In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split as tts
import matplotlib.pyplot as plt
import numpy as np


In [2]:
salary=pd.read_csv('D:\\Naive Bayes assign 12\\SalaryData_Test.csv')

In [3]:
salary

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [4]:
#x is the matrix of features it contains independent variable number 0 and 13 which is Age,Estimatedsalary according to dataset
X=salary.iloc[:,[0,3]].values
#Y=contains dependent variable which is purchased according to dataset and the column number is 11
Y=salary.iloc[:,10].values

In [5]:
#printing the independent variables matrix
X

array([[25,  7],
       [38,  9],
       [28, 12],
       ...,
       [38, 13],
       [44, 13],
       [35, 13]], dtype=int64)

In [6]:
Y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [8]:
#splitting x and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [9]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[51  2]
 [60 10]
 [31 14]
 ...
 [40 12]
 [62 10]
 [31  9]]
[[42 10]
 [36 14]
 [53 10]
 ...
 [36  9]
 [30 10]
 [39  9]]
[0 0 0 ... 0 0 0]
[   0 1887    0 ...    0    0    0]


In [10]:
#training the model on tarining set
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,Y_train)

GaussianNB()

In [11]:
Y_pred=gnb.predict(X_train)
Y_pred

array([   0, 1944,    0, ...,    0, 1944,    0], dtype=int64)

In [12]:
from sklearn import metrics
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_train,Y_pred))
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_train,Y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 0.9166666666666666
Gaussian Naive Bayes model accuracy(in %): 91.66666666666666


In [13]:
#making predictions on the testing set
Y_pred=gnb.predict(X_test)

In [15]:
Y_pred

array([213,   0,   0, ...,   0,   0,   0], dtype=int64)

In [17]:
#comparing actual response values (Y_test)with predict response values(Y_pred)
from sklearn import metrics
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_test,Y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 91.50066401062416
