In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split as tts
import matplotlib.pyplot as plt
import numpy as np

In [2]:
salary=pd.read_csv('D:\\Naive Bayes assign 12\\SalaryData_Train.csv')

In [3]:
salary

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
#x is the matrix of features it contains independent variable number 0 and 13 which is Age,Estimatedsalary according to dataset
X=salary.iloc[:,[0,3]].values
#Y=contains dependent variable which is purchased according to dataset and the column number is 11
Y=salary.iloc[:,10].values

In [5]:
#printing the independent variables matrix
X

array([[39, 13],
       [50, 13],
       [38,  9],
       ...,
       [58,  9],
       [22,  9],
       [52,  9]], dtype=int64)

In [6]:
Y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [7]:
#splitting x and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [8]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[46  9]
 [39  7]
 [37  3]
 ...
 [17  6]
 [42  9]
 [45 13]]
[[24  9]
 [45 13]
 [26  9]
 ...
 [23  9]
 [40  9]
 [40  9]]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [9]:
#training the model on tarining set
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,Y_train)

GaussianNB()

In [10]:
Y_pred=gnb.predict(X_train)
Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
from sklearn import metrics
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_train,Y_pred))
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_train,Y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 0.8475215517241379
Gaussian Naive Bayes model accuracy(in %): 84.7521551724138


In [12]:
#making predictions on the testing set
Y_pred=gnb.predict(X_test)

In [13]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
#comparing actual response values (Y_test)with predict response values(Y_pred)
from sklearn import metrics
print('Gaussian Naive Bayes model accuracy(in %):',metrics.accuracy_score(Y_test,Y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 84.71738770097795
